### ISSUE TITLE
weights dimensional issue

### ISSUE THREAD

**Issue by weizhou-geek** [YapengTian/SRCNN-Keras#1]
Hi,

I ran the training code, and then get the srcnn_keras.mat which saves the weights and bias. But the dimension for weights are 4D single, 64*32 single, and 4D single. The results are not consistent with the one in test folder (4D single, 4D single, and 5*5*32 single)?

**Comment by YapengTian** [comment]
What is your keras version? This code is based on Keras-1.

**Comment by weizhou-geek** [comment]
My keras version is Keras-2. But I have tried to use Keras-1, the problem still happened.

**Comment by YapengTian** [comment]
So, you need to rewrite a converter.

**Comment by weizhou-geek** [comment]
Yes, the backend for Keras that I used is TensorFlow, So I rewrite the load_save for saving weights. The problem has been solved, thank you!
